    filename = 'test.tikz';
    cleanfigure('minimumPointsDistance', 1/10);
    matlab2tikz(filename,...
        'showInfo', false,...
        'height', '\figureheight', 'width', '\figurewidth');
%         'extraAxisOptions',...
%         ['xlabel style={font=\footnotesize},'...
%         'ylabel style={font=\footnotesize},',...
%         'legend style={font=\footnotesize},',...
%         'ticklabel style={font=\scriptsize}']);